#!/bin/sh

### BEGIN INIT INFO 
# Provides:          update_db
# Required-Start:
# Should-Start:  network
# Required-Stop:
# Default-Start: 3 5
# Default-Stop:  0 1 2 4 6
# Short-Description: update db ip address in tnsnames.ora
# Description:
#
### END INIT INFO


# **********************************************************************
# Copyright (c) 2011 Ericsson Software Technology AB, Sweden.
# All rights reserved.
# The Copyright to the computer program(s) herein is the property of
# Ericsson Software Technology AB, Sweden.
# The program(s) may be used and/or copied with the written permission
# from Ericsson Software Technology AB or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the
# program(s) have been supplied.
# **********************************************************************

. /etc/rc.status

CURRENTUID=`id -u`

if [ $CURRENTUID != "0" ]; then
    echo this script must run as root!
    exit;
fi

case "$1" in
start)
    ip=`curl http://192.168.4.1:9393/db 2>/dev/null`
    if [ "X$ip" == "X" ] ; then
        rc_failed 2
        rc_status -v
        rc_exit
    fi
    sed "s/\${db}/$ip/g" /var/sog/data/database/tnsnames.ora.template > /var/sog/data/database/tnsnames.ora
    chown sogadm:sog /var/sog/data/database/tnsnames.ora
    chmod 755 /var/sog/data/database/tnsnames.ora
    rc_status -v
    ;;
stop)
    rc_status -v
    ;;
restart)
    $0 stop
    $0 start
    rc_status
    ;;
*)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
rc_exit

